// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbNKlTNEslaIwnePX_xn11ybXt5p03fBA',
    appId: '1:519976640642:web:103f43e6b17ac20d6ed49b',
    messagingSenderId: '519976640642',
    projectId: 'notes-flutter-project-one',
    authDomain: 'notes-flutter-project-one.firebaseapp.com',
    storageBucket: 'notes-flutter-project-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHFNB-Q6f1czFhTMpyrnIQCEAdVWntYE',
    appId: '1:519976640642:android:d3b0f5b1116a6c2c6ed49b',
    messagingSenderId: '519976640642',
    projectId: 'notes-flutter-project-one',
    storageBucket: 'notes-flutter-project-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75VNk42foICac5h8VFppg7IqVmLFtbfY',
    appId: '1:519976640642:ios:fbd61f360ab50f466ed49b',
    messagingSenderId: '519976640642',
    projectId: 'notes-flutter-project-one',
    storageBucket: 'notes-flutter-project-one.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75VNk42foICac5h8VFppg7IqVmLFtbfY',
    appId: '1:519976640642:ios:d33e29d33751e5cc6ed49b',
    messagingSenderId: '519976640642',
    projectId: 'notes-flutter-project-one',
    storageBucket: 'notes-flutter-project-one.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
